### PR TITLE
Clean up Services layout #157613732

### PR DESCRIPTION
**Pull request by cknific**
# What was done
* Update styles in all sections
* Fix bug in services list with poorly wrapping text
* Make contact us button larger
* Ensure background colors in each section alternate
* Clean up HTML file

## Finishes
#157613732

### Screenshot
services

### CODE REVIEW

**Comment by cknific** [comment]
@phlipper something screwy happened here on my rebase (see "fixup" commit I tried to rebase away and conflicting `services.html` file). I've got a conflict here I could use your eyes on.

@taylorculver any feedback on the screenshot? Again, I could keep going, and am pausing at 1.75 hours.

**Comment by phlipper** [comment]
@cknific I looked in to the rebase issue and we should grab a few minutes to chat.

**Comment by taylorculver** [comment]
@cknific @phlipper - good work. For the Areas of focus, can you add a full bar at the bottom where data governance is for data strategy, place data architecture above that, and place data governance above that? Only analytics and product development should be split 50/50. Otherwise good stuff.

**Comment by taylorculver** [comment]
@cknific if you could start resolving the conflicts that would be great! Approved the changes.

**Comment by cknific** [comment]
@taylorculver great, thank you. We're going to start untangling things this afternoon.

**Pull request merged**
